# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashCard_Gamescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName("Game")
        Game.resize(920, 620)
        Game.setMinimumSize(QtCore.QSize(920, 620))
        Game.setMaximumSize(QtCore.QSize(920, 620))
        Game.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(Game)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Game)
        self.widget.setMouseTracking(True)
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,255), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,255,0,255), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,255), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(255,0,0,255), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "QPushButton#quitButton{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,255), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#quitButton:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(255,0,0,255), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#quitButton:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "QPushButton#settime{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(11,131,120,219), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#settime:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(150,123,11,219), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#settime:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "QLabel#lt_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#lb_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#rt_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "\n"
                                  "}\n"
                                  "QLabel#rb_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.background = QtWidgets.QLabel(self.widget)
        self.background.setGeometry(QtCore.QRect(30, 30, 841, 541))
        font = QtGui.QFont()
        font.setKerning(True)
        self.background.setFont(font)
        self.background.setStyleSheet("\\\\border-image: url(:/image/D.png);\n"
                                      "background-color: rgb(255,255,255);\n"
                                      "border-top-right-radius: 25px;\n"
                                      "border-bottom-right-radius: 25px;\n"
                                      "border-top-left-radius: 25px;\n"
                                      "border-bottom-left-radius: 25px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.quitButton = QtWidgets.QPushButton(self.widget)
        self.quitButton.setGeometry(QtCore.QRect(740, 43, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.quitButton.setFont(font)
        self.quitButton.setObjectName("quitButton")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 490, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-top-right-radius: 35px;\n"
                                      "border-bottom-right-radius:35px;\n"
                                      "border-top-left-radius: 35px;\n"
                                      "border-bottom-left-radius: 35px;")
        self.pushButton.setObjectName("pushButton")
        self.fcard = QtWidgets.QLabel(self.widget)
        self.fcard.setGeometry(QtCore.QRect(258, 115, 391, 361))
        self.fcard.setStyleSheet("border-top-right-radius: 40px;\n"
                                 "border-bottom-right-radius: 40px;\n"
                                 "border-top-left-radius: 40px;\n"
                                 "border-bottom-left-radius: 40px;\n"
                                 "border-width: 8px;border-style: solid;border-color: rgb(50, 179, 226);background-color: rgb(3, 151, 157);")
        self.fcard.setText("")
        self.fcard.setObjectName("fcard")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 490, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-top-right-radius: 35px;\n"
                                        "border-bottom-right-radius:35px;\n"
                                        "border-top-left-radius: 35px;\n"
                                        "border-bottom-left-radius: 35px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.language = QtWidgets.QLabel(self.widget)
        self.language.setGeometry(QtCore.QRect(364, 150, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(22)
        self.language.setFont(font)
        self.language.setStyleSheet("\n"
                                    "color: rgb(255, 255, 0);\n"
                                    "")
        self.language.setObjectName("language")
        self.words = QtWidgets.QLabel(self.widget)
        self.words.setGeometry(QtCore.QRect(340, 290, 231, 111))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(36)
        self.words.setFont(font)
        self.words.setStyleSheet("color: rgb(255,255,255);")
        self.words.setObjectName("words")
        self.level = QtWidgets.QLabel(self.widget)
        self.level.setGeometry(QtCore.QRect(150, 50, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.level.setFont(font)
        self.level.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.level.setToolTipDuration(-4)
        self.level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.level.setStyleSheet("color: rgb(85，170，127);\n"
                                 "")
        self.level.setObjectName("level")
        self.time = QtWidgets.QLabel(self.widget)
        self.time.setGeometry(QtCore.QRect(110, 130, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(26)
        self.time.setFont(font)
        self.time.setStyleSheet("\n"
                                "color: rgb(0, 0, 103);")
        self.time.setObjectName("time")
        self.sleeptime = QtWidgets.QLabel(self.widget)
        self.sleeptime.setGeometry(QtCore.QRect(120, 190, 72, 101))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(74)
        self.sleeptime.setFont(font)
        self.sleeptime.setObjectName("sleeptime")
        self.lt_b = QtWidgets.QLabel(self.widget)
        self.lt_b.setGeometry(QtCore.QRect(77, 117, 152, 198))
        self.lt_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "background-color: rgb(77, 159, 232);\n"
                                "border-bottom-left-radius: 10px;\n"
                                "border-width: 5px;border-style: solid;border-color: rgb(77, 159, 232);background-color: rgb(92, 225, 230);")
        self.lt_b.setText("")
        self.lt_b.setObjectName("lt_b")
        self.lt_f = QtWidgets.QLabel(self.widget)
        self.lt_f.setGeometry(QtCore.QRect(80, 120, 146, 192))
        self.lt_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;")
        self.lt_f.setText("")
        self.lt_f.setObjectName("lt_f")
        self.lb_f = QtWidgets.QLabel(self.widget)
        self.lb_f.setGeometry(QtCore.QRect(80, 333, 146, 192))
        self.lb_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;")
        self.lb_f.setText("")
        self.lb_f.setObjectName("lb_f")
        self.lb_b = QtWidgets.QLabel(self.widget)
        self.lb_b.setGeometry(QtCore.QRect(77, 330, 152, 198))
        self.lb_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;\n"
                                "border-width: 5px;border-style: solid;border-color: rgb(255, 164, 164);background-color: rgb(199, 223, 100);")
        self.lb_b.setText("")
        self.lb_b.setObjectName("lb_b")
        self.rb_b = QtWidgets.QLabel(self.widget)
        self.rb_b.setGeometry(QtCore.QRect(677, 327, 152, 198))
        self.rb_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;\n"
                                "border-width: 5px;border-style: solid;border-color: rgb(201, 226, 101);background-color: rgb(255, 164, 164);")
        self.rb_b.setText("")
        self.rb_b.setObjectName("rb_b")
        self.rt_b = QtWidgets.QLabel(self.widget)
        self.rt_b.setGeometry(QtCore.QRect(677, 117, 152, 198))
        self.rt_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;\n"
                                "border-width: 5px;border-style: solid;border-color: rgb(203, 175, 241);background-color: rgb(77, 159, 232);")
        self.rt_b.setText("")
        self.rt_b.setObjectName("rt_b")
        self.rt_f = QtWidgets.QLabel(self.widget)
        self.rt_f.setGeometry(QtCore.QRect(680, 120, 146, 192))
        self.rt_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;")
        self.rt_f.setText("")
        self.rt_f.setObjectName("rt_f")
        self.timeinput = QtWidgets.QLineEdit(self.widget)
        self.timeinput.setGeometry(QtCore.QRect(105, 371, 100, 40))
        self.timeinput.setAccessibleName("")
        self.timeinput.setStyleSheet("color: rgba(0,0,0,255);\n"
                                     "background-color: rgb(145, 197, 206);\n"
                                     "font: 9pt \"Arial\";\n"
                                     "border-top-right-radius: 5px;\n"
                                     "border-bottom-right-radius: 5px;\n"
                                     "border-top-left-radius: 5px;\n"
                                     "border-bottom-left-radius: 5px;\n"
                                     "border-width: 1px;border-style: solid;border-color: rgb(0, 0, 0);background-color: rgb(145, 197, 206);")
        self.timeinput.setText("")
        self.timeinput.setAlignment(QtCore.Qt.AlignCenter)
        self.timeinput.setDragEnabled(False)
        self.timeinput.setPlaceholderText("Second")
        self.timeinput.setObjectName("timeinput")
        self.settime = QtWidgets.QPushButton(self.widget)
        self.settime.setGeometry(QtCore.QRect(105, 440, 100, 40))
        self.settime.setObjectName("settime")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(719, 120, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
                                 "color: rgb(0, 255, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(710, 330, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(49)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.point1 = QtWidgets.QLabel(self.widget)
        self.point1.setGeometry(QtCore.QRect(681, 194, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(55)
        self.point1.setFont(font)
        self.point1.setStyleSheet("color: rgb(0, 170, 127);\n"
                                  "color: rgb(85, 255, 127);")
        self.point1.setAlignment(QtCore.Qt.AlignCenter)
        self.point1.setObjectName("point1")
        self.point2 = QtWidgets.QLabel(self.widget)
        self.point2.setGeometry(QtCore.QRect(681, 410, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(55)
        font.setKerning(True)
        self.point2.setFont(font)
        self.point2.setStyleSheet("color: rgb(255, 0, 0);")
        self.point2.setAlignment(QtCore.Qt.AlignCenter)
        self.point2.setObjectName("point2")
        self.rb_f = QtWidgets.QLabel(self.widget)
        self.rb_f.setGeometry(QtCore.QRect(680, 330, 146, 192))
        self.rb_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                "border-bottom-right-radius: 10px;\n"
                                "border-top-left-radius: 10px;\n"
                                "border-bottom-left-radius: 10px;")
        self.rb_f.setText("")
        self.rb_f.setObjectName("rb_f")
        self.progressBar_ingame = QtWidgets.QProgressBar(self.widget)
        self.progressBar_ingame.setGeometry(QtCore.QRect(230, 50, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.progressBar_ingame.setFont(font)
        self.progressBar_ingame.setProperty("value", 65)
        self.progressBar_ingame.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_ingame.setObjectName("progressBar_ingame")
        self.background.raise_()
        self.quitButton.raise_()
        self.pushButton.raise_()
        self.fcard.raise_()
        self.pushButton_2.raise_()
        self.language.raise_()
        self.level.raise_()
        self.lt_b.raise_()
        self.lb_b.raise_()
        self.rb_b.raise_()
        self.rt_b.raise_()
        self.words.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.point2.raise_()
        self.lb_f.raise_()
        self.point1.raise_()
        self.settime.raise_()
        self.sleeptime.raise_()
        self.time.raise_()
        self.timeinput.raise_()
        self.rb_f.raise_()
        self.rt_f.raise_()
        self.lt_f.raise_()
        self.progressBar_ingame.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Game)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        _translate = QtCore.QCoreApplication.translate
        Game.setWindowTitle(_translate("Game", "Form"))
        self.quitButton.setText(_translate("Game", "Back"))
        self.pushButton.setText(_translate("Game", "True"))
        self.pushButton_2.setText(_translate("Game", "False"))
        self.language.setText(_translate("Game", "Nederlands"))
        self.words.setText(_translate("Game", "Woorden"))
        self.level.setText(_translate("Game", "level"))
        self.time.setText(_translate("Game", "Time"))
        self.sleeptime.setText(_translate("Game", "3"))
        self.settime.setText(_translate("Game", "set timer"))
        self.label.setText(_translate("Game", "✔"))
        self.label_2.setText(_translate("Game", "✘"))
        self.point1.setText(_translate("Game", "10"))
        self.point2.setText(_translate("Game", "10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Game = QtWidgets.QWidget()
    ui = Ui_Game()
    ui.setupUi(Game)
    Game.show()
    sys.exit(app.exec_())
