# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashCard_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(920, 620)
        menu.setMinimumSize(QtCore.QSize(920, 620))
        menu.setMaximumSize(QtCore.QSize(920, 620))
        menu.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(menu)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(menu)
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,255), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(255,0,0,255), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#quitButton_2{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,255), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#quitButton_2:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(255,0,0,255), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#quitButton_2:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "QLabel#label_F_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_L_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_A_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_S_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_H_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_C_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_2A_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_R_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_D_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_S2_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "\n"
                                  "\n"
                                  "\n"
                                  "\n"
                                  "")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 841, 541))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-top-right-radius: 25px;\n"
                                 "border-bottom-right-radius: 25px;\n"
                                 "border-top-left-radius: 25px;\n"
                                 "border-bottom-left-radius: 25px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_welcome = QtWidgets.QLabel(self.widget)
        self.label_welcome.setGeometry(QtCore.QRect(60, 250, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("color: rgb(3, 151, 157);")
        self.label_welcome.setObjectName("label_welcome")
        self.quitButton_2 = QtWidgets.QPushButton(self.widget)
        self.quitButton_2.setGeometry(QtCore.QRect(728, 250, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.quitButton_2.setFont(font)
        self.quitButton_2.setObjectName("quitButton_2")
        self.label_username = QtWidgets.QLabel(self.widget)
        self.label_username.setGeometry(QtCore.QRect(262, 250, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.label_username.setFont(font)
        self.label_username.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_username.setToolTipDuration(-4)
        self.label_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_username.setStyleSheet("color: rgb(0, 0, 173);")
        self.label_username.setObjectName("label_username")
        self.progressBar_menu = QtWidgets.QProgressBar(self.widget)
        self.progressBar_menu.setGeometry(QtCore.QRect(60, 310, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.progressBar_menu.setFont(font)
        self.progressBar_menu.setProperty("value", 60)
        self.progressBar_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_menu.setObjectName("progressBar_menu")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(570, 250, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-top-right-radius: 50px;\n"
                                      "border-bottom-right-radius: 50px;\n"
                                      "border-top-left-radius: 50px;\n"
                                      "border-bottom-left-radius: 50px;")
        self.pushButton.setObjectName("pushButton")
        self.label_L_s = QtWidgets.QLabel(self.widget)
        self.label_L_s.setGeometry(QtCore.QRect(262, 68, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_L_s.setFont(font)
        self.label_L_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_L_s.setObjectName("label_L_s")
        self.label_R = QtWidgets.QLabel(self.widget)
        self.label_R.setGeometry(QtCore.QRect(407, 375, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_R.setFont(font)
        self.label_R.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_R.setObjectName("label_R")
        self.label_A_s = QtWidgets.QLabel(self.widget)
        self.label_A_s.setGeometry(QtCore.QRect(417, 67, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_A_s.setFont(font)
        self.label_A_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_A_s.setObjectName("label_A_s")
        self.label_H_f = QtWidgets.QLabel(self.widget)
        self.label_H_f.setGeometry(QtCore.QRect(707, 47, 146, 192))
        self.label_H_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_H_f.setText("")
        self.label_H_f.setObjectName("label_H_f")
        self.label_H = QtWidgets.QLabel(self.widget)
        self.label_H.setGeometry(QtCore.QRect(730, 60, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_H.setFont(font)
        self.label_H.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_H.setObjectName("label_H")
        self.label_H_s = QtWidgets.QLabel(self.widget)
        self.label_H_s.setGeometry(QtCore.QRect(740, 67, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_H_s.setFont(font)
        self.label_H_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_H_s.setObjectName("label_H_s")
        self.label_L_b = QtWidgets.QLabel(self.widget)
        self.label_L_b.setGeometry(QtCore.QRect(217, 44, 152, 198))
        self.label_L_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "color: rgb(203, 175, 241);\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(203, 175, 241);background-color: rgb(255, 122, 92);")
        self.label_L_b.setText("")
        self.label_L_b.setObjectName("label_L_b")
        self.label_R_f = QtWidgets.QLabel(self.widget)
        self.label_R_f.setGeometry(QtCore.QRect(383, 364, 146, 192))
        self.label_R_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_R_f.setText("")
        self.label_R_f.setObjectName("label_R_f")
        self.label_L_f = QtWidgets.QLabel(self.widget)
        self.label_L_f.setGeometry(QtCore.QRect(220, 47, 146, 192))
        self.label_L_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_L_f.setText("")
        self.label_L_f.setObjectName("label_L_f")
        self.label_A = QtWidgets.QLabel(self.widget)
        self.label_A.setGeometry(QtCore.QRect(407, 60, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_A.setObjectName("label_A")
        self.label_2A_s = QtWidgets.QLabel(self.widget)
        self.label_2A_s.setGeometry(QtCore.QRect(257, 382, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_2A_s.setFont(font)
        self.label_2A_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                      "")
        self.label_2A_s.setObjectName("label_2A_s")
        self.label_F_f = QtWidgets.QLabel(self.widget)
        self.label_F_f.setGeometry(QtCore.QRect(56, 47, 146, 192))
        self.label_F_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_F_f.setText("")
        self.label_F_f.setObjectName("label_F_f")
        self.label_D = QtWidgets.QLabel(self.widget)
        self.label_D.setGeometry(QtCore.QRect(572, 375, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_D.setFont(font)
        self.label_D.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_D.setObjectName("label_D")
        self.label_F = QtWidgets.QLabel(self.widget)
        self.label_F.setGeometry(QtCore.QRect(87, 61, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_F.setFont(font)
        self.label_F.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_F.setObjectName("label_F")
        self.label_F_s = QtWidgets.QLabel(self.widget)
        self.label_F_s.setGeometry(QtCore.QRect(97, 68, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_F_s.setFont(font)
        self.label_F_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_F_s.setObjectName("label_F_s")
        self.label_S2_f = QtWidgets.QLabel(self.widget)
        self.label_S2_f.setGeometry(QtCore.QRect(707, 364, 146, 192))
        self.label_S2_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;")
        self.label_S2_f.setText("")
        self.label_S2_f.setObjectName("label_S2_f")
        self.label_A_b = QtWidgets.QLabel(self.widget)
        self.label_A_b.setGeometry(QtCore.QRect(379, 44, 152, 198))
        self.label_A_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 189, 89);background-color: rgb(217, 217, 217);")
        self.label_A_b.setText("")
        self.label_A_b.setObjectName("label_A_b")
        self.label_H_b = QtWidgets.QLabel(self.widget)
        self.label_H_b.setGeometry(QtCore.QRect(704, 44, 152, 198))
        self.label_H_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(92, 225, 230);background-color: rgb(77, 159, 232);")
        self.label_H_b.setText("")
        self.label_H_b.setObjectName("label_H_b")
        self.label_2A = QtWidgets.QLabel(self.widget)
        self.label_2A.setGeometry(QtCore.QRect(247, 375, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_2A.setFont(font)
        self.label_2A.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2A.setObjectName("label_2A")
        self.label_D_s = QtWidgets.QLabel(self.widget)
        self.label_D_s.setGeometry(QtCore.QRect(582, 382, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_D_s.setFont(font)
        self.label_D_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_D_s.setObjectName("label_D_s")
        self.label_D_f = QtWidgets.QLabel(self.widget)
        self.label_D_f.setGeometry(QtCore.QRect(545, 364, 146, 192))
        self.label_D_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_D_f.setText("")
        self.label_D_f.setObjectName("label_D_f")
        self.label_S2_b = QtWidgets.QLabel(self.widget)
        self.label_S2_b.setGeometry(QtCore.QRect(704, 361, 152, 198))
        self.label_S2_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;\n"
                                      "border-width: 5px;border-style: solid;border-color: rgb(201, 226, 101);background-color: rgb(255, 164, 164);")
        self.label_S2_b.setText("")
        self.label_S2_b.setObjectName("label_S2_b")
        self.label_S2_s = QtWidgets.QLabel(self.widget)
        self.label_S2_s.setGeometry(QtCore.QRect(742, 382, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S2_s.setFont(font)
        self.label_S2_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                      "")
        self.label_S2_s.setObjectName("label_S2_s")
        self.label_S_b = QtWidgets.QLabel(self.widget)
        self.label_S_b.setGeometry(QtCore.QRect(542, 44, 152, 198))
        self.label_S_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(166, 166, 166);background-color: rgb(203, 175, 241);")
        self.label_S_b.setText("")
        self.label_S_b.setObjectName("label_S_b")
        self.label_A_f = QtWidgets.QLabel(self.widget)
        self.label_A_f.setGeometry(QtCore.QRect(382, 47, 146, 192))
        self.label_A_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_A_f.setText("")
        self.label_A_f.setObjectName("label_A_f")
        self.label_2A_f = QtWidgets.QLabel(self.widget)
        self.label_2A_f.setGeometry(QtCore.QRect(220, 364, 146, 192))
        self.label_2A_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;")
        self.label_2A_f.setText("")
        self.label_2A_f.setObjectName("label_2A_f")
        self.label_C = QtWidgets.QLabel(self.widget)
        self.label_C.setGeometry(QtCore.QRect(79, 375, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_C.setObjectName("label_C")
        self.label_R_s = QtWidgets.QLabel(self.widget)
        self.label_R_s.setGeometry(QtCore.QRect(417, 382, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_R_s.setFont(font)
        self.label_R_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_R_s.setObjectName("label_R_s")
        self.label_R_b = QtWidgets.QLabel(self.widget)
        self.label_R_b.setGeometry(QtCore.QRect(379, 361, 152, 198))
        self.label_R_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(50, 179, 226);background-color: rgb(3, 151, 157);")
        self.label_R_b.setText("")
        self.label_R_b.setObjectName("label_R_b")
        self.label_S_f = QtWidgets.QLabel(self.widget)
        self.label_S_f.setGeometry(QtCore.QRect(545, 47, 146, 192))
        self.label_S_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_S_f.setText("")
        self.label_S_f.setObjectName("label_S_f")
        self.label_S_s = QtWidgets.QLabel(self.widget)
        self.label_S_s.setGeometry(QtCore.QRect(580, 67, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S_s.setFont(font)
        self.label_S_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_S_s.setObjectName("label_S_s")
        self.label_S = QtWidgets.QLabel(self.widget)
        self.label_S.setGeometry(QtCore.QRect(570, 60, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S.setFont(font)
        self.label_S.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_S.setObjectName("label_S")
        self.label_S2 = QtWidgets.QLabel(self.widget)
        self.label_S2.setGeometry(QtCore.QRect(732, 375, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S2.setFont(font)
        self.label_S2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_S2.setObjectName("label_S2")
        self.label_D_b = QtWidgets.QLabel(self.widget)
        self.label_D_b.setGeometry(QtCore.QRect(542, 361, 152, 198))
        self.label_D_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "color: rgb(255, 85, 0);\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 85, 0);background-color: rgb(231, 92, 178);")
        self.label_D_b.setText("")
        self.label_D_b.setObjectName("label_D_b")
        self.label_C_f = QtWidgets.QLabel(self.widget)
        self.label_C_f.setGeometry(QtCore.QRect(56, 364, 146, 192))
        self.label_C_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_C_f.setText("")
        self.label_C_f.setObjectName("label_C_f")
        self.label_C_b = QtWidgets.QLabel(self.widget)
        self.label_C_b.setGeometry(QtCore.QRect(53, 361, 152, 198))
        self.label_C_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 164, 164);background-color: rgb(199, 223, 100);")
        self.label_C_b.setText("")
        self.label_C_b.setObjectName("label_C_b")
        self.label_C_s = QtWidgets.QLabel(self.widget)
        self.label_C_s.setGeometry(QtCore.QRect(89, 382, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_C_s.setFont(font)
        self.label_C_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_C_s.setObjectName("label_C_s")
        self.label_2A_b = QtWidgets.QLabel(self.widget)
        self.label_2A_b.setGeometry(QtCore.QRect(217, 361, 152, 198))
        self.label_2A_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;\n"
                                      "border-width: 5px;border-style: solid;border-color: rgb(203, 175, 241);background-color: rgb(255, 189, 89);")
        self.label_2A_b.setText("")
        self.label_2A_b.setObjectName("label_2A_b")
        self.label_L = QtWidgets.QLabel(self.widget)
        self.label_L.setGeometry(QtCore.QRect(252, 61, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_L.setFont(font)
        self.label_L.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_L.setObjectName("label_L")
        self.label_F_b = QtWidgets.QLabel(self.widget)
        self.label_F_b.setGeometry(QtCore.QRect(53, 44, 152, 198))
        self.label_F_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "background-color: rgb(77, 159, 232);\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(77, 159, 232);background-color: rgb(92, 225, 230);")
        self.label_F_b.setText("")
        self.label_F_b.setObjectName("label_F_b")
        self.label.raise_()
        self.label_welcome.raise_()
        self.quitButton_2.raise_()
        self.label_username.raise_()
        self.progressBar_menu.raise_()
        self.pushButton.raise_()
        self.label_L_b.raise_()
        self.label_A_b.raise_()
        self.label_H_b.raise_()
        self.label_S2_b.raise_()
        self.label_S_b.raise_()
        self.label_R_b.raise_()
        self.label_D_b.raise_()
        self.label_C_b.raise_()
        self.label_2A_b.raise_()
        self.label_F_b.raise_()
        self.label_2A_s.raise_()
        self.label_2A.raise_()
        self.label_2A_f.raise_()
        self.label_A_s.raise_()
        self.label_A.raise_()
        self.label_A_f.raise_()
        self.label_C_s.raise_()
        self.label_C.raise_()
        self.label_C_f.raise_()
        self.label_D_s.raise_()
        self.label_D_f.raise_()
        self.label_D.raise_()
        self.label_F_s.raise_()
        self.label_F.raise_()
        self.label_F_f.raise_()
        self.label_H_s.raise_()
        self.label_H.raise_()
        self.label_H_f.raise_()
        self.label_L_s.raise_()
        self.label_L.raise_()
        self.label_L_f.raise_()
        self.label_R_s.raise_()
        self.label_R.raise_()
        self.label_R_f.raise_()
        self.label_S_s.raise_()
        self.label_S.raise_()
        self.label_S_f.raise_()
        self.label_S2_s.raise_()
        self.label_S2.raise_()
        self.label_S2_f.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Form"))
        self.label_welcome.setText(_translate("menu", "Welcom back"))
        self.quitButton_2.setText(_translate("menu", "Quit"))
        self.label_username.setText(_translate("menu", "User Name"))
        self.pushButton.setText(_translate("menu", "Play"))
        self.label_L_s.setText(_translate("menu", "L"))
        self.label_R.setText(_translate("menu", "R"))
        self.label_A_s.setText(_translate("menu", "A"))
        self.label_H.setText(_translate("menu", "H"))
        self.label_H_s.setText(_translate("menu", "H"))
        self.label_A.setText(_translate("menu", "A"))
        self.label_2A_s.setText(_translate("menu", "A"))
        self.label_D.setText(_translate("menu", "D"))
        self.label_F.setText(_translate("menu", "F"))
        self.label_F_s.setText(_translate("menu", "F"))
        self.label_2A.setText(_translate("menu", "A"))
        self.label_D_s.setText(_translate("menu", "D"))
        self.label_S2_s.setText(_translate("menu", "S"))
        self.label_C.setText(_translate("menu", "C"))
        self.label_R_s.setText(_translate("menu", "R"))
        self.label_S_s.setText(_translate("menu", "S"))
        self.label_S.setText(_translate("menu", "S"))
        self.label_S2.setText(_translate("menu", "S"))
        self.label_C_s.setText(_translate("menu", "C"))
        self.label_L.setText(_translate("menu", "L"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QWidget()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
