# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashCard_LOGIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login import User

class Ui_Login(object):
    def login(self):
        user = User(self.lineEdit_username.text())
        user.login()
    def closeIt(self,close): 
        self.close()
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(920, 620)
        Login.setMinimumSize(QtCore.QSize(920, 620))
        Login.setMaximumSize(QtCore.QSize(920, 620))
        Login.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(11,131,120,219), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(150,123,11,219), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(11,131,120,219), stop:1 rgba(85,98,112,226));\n"
                                  "    color:rgba(255,255,255,210);\n"
                                  "    border-radius:5px\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(150,123,11,219), stop:1 rgba(85,81,84,226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150,123,1,255);\n"
                                  "}\n"
                                  "\n"
                                  "\n"
                                  "QLabel#label_F_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_L_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_A_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_S_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_H_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_C_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_2A_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_R_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_D_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "QLabel#label_S2_f:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.50682, x2:1, y2:0.477, stop:0 rgba(0,0,0,85), stop:1 rgba(50,50,50,150));\n"
                                  "}\n"
                                  "")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 841, 541))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-top-right-radius: 25px;\n"
                                 "border-bottom-right-radius: 25px;\n"
                                 "border-top-left-radius: 25px;\n"
                                 "border-bottom-left-radius: 25px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_login = QtWidgets.QLabel(self.widget)
        self.label_login.setGeometry(QtCore.QRect(70, 270, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(30)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color: rgb(3, 151, 157);")
        self.label_login.setObjectName("label_login")
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_username.setGeometry(QtCore.QRect(400, 278, 200, 41))
        self.lineEdit_username.setAccessibleName("")
        self.lineEdit_username.setStyleSheet("color: rgba(0,0,0,255);\n"
                                             "background-color: rgb(145, 197, 206);\n"
                                             "font: 9pt \"Arial\";\n"
                                             "border-top-right-radius: 5px;\n"
                                             "border-bottom-right-radius: 5px;\n"
                                             "border-top-left-radius: 5px;\n"
                                             "border-bottom-left-radius: 5px;\n"
                                             "border-width: 1px;border-style: solid;border-color: rgb(0, 0, 0);background-color: rgb(145, 197, 206);")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_username.setDragEnabled(False)
        self.lineEdit_username.setPlaceholderText("User Name")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(630, 254, 200, 40))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.setCheckable(True)  #yeni eklendi
        self.pushButton.clicked.connect(self.login)  #yeni eklendi

        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 305, 200, 40))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.setCheckable(True)  # cancel bottun
        self.pushButton_2.clicked.connect(self.closeIt) #click cancel bottun to close 

        self.label_L_f = QtWidgets.QLabel(self.widget)
        self.label_L_f.setGeometry(QtCore.QRect(218, 46, 146, 192))
        self.label_L_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_L_f.setText("")
        self.label_L_f.setObjectName("label_L_f")
        self.label_L_b = QtWidgets.QLabel(self.widget)
        self.label_L_b.setGeometry(QtCore.QRect(215, 43, 152, 198))
        self.label_L_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "color: rgb(203, 175, 241);\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(203, 175, 241);background-color: rgb(255, 122, 92);")
        self.label_L_b.setText("")
        self.label_L_b.setObjectName("label_L_b")
        self.label_L = QtWidgets.QLabel(self.widget)
        self.label_L.setGeometry(QtCore.QRect(250, 60, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_L.setFont(font)
        self.label_L.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_L.setObjectName("label_L")
        self.label_L_s = QtWidgets.QLabel(self.widget)
        self.label_L_s.setGeometry(QtCore.QRect(260, 67, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_L_s.setFont(font)
        self.label_L_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_L_s.setObjectName("label_L_s")
        self.label_F_f = QtWidgets.QLabel(self.widget)
        self.label_F_f.setGeometry(QtCore.QRect(54, 46, 146, 192))
        self.label_F_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_F_f.setText("")
        self.label_F_f.setObjectName("label_F_f")
        self.label_F = QtWidgets.QLabel(self.widget)
        self.label_F.setGeometry(QtCore.QRect(85, 60, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_F.setFont(font)
        self.label_F.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_F.setObjectName("label_F")
        self.label_F_b = QtWidgets.QLabel(self.widget)
        self.label_F_b.setGeometry(QtCore.QRect(51, 43, 152, 198))
        self.label_F_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "background-color: rgb(77, 159, 232);\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(77, 159, 232);background-color: rgb(92, 225, 230);")
        self.label_F_b.setText("")
        self.label_F_b.setObjectName("label_F_b")
        self.label_F_s = QtWidgets.QLabel(self.widget)
        self.label_F_s.setGeometry(QtCore.QRect(95, 67, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_F_s.setFont(font)
        self.label_F_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_F_s.setObjectName("label_F_s")
        self.label_A_f = QtWidgets.QLabel(self.widget)
        self.label_A_f.setGeometry(QtCore.QRect(380, 46, 146, 192))
        self.label_A_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_A_f.setText("")
        self.label_A_f.setObjectName("label_A_f")
        self.label_A_b = QtWidgets.QLabel(self.widget)
        self.label_A_b.setGeometry(QtCore.QRect(377, 43, 152, 198))
        self.label_A_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 189, 89);background-color: rgb(217, 217, 217);")
        self.label_A_b.setText("")
        self.label_A_b.setObjectName("label_A_b")
        self.label_A = QtWidgets.QLabel(self.widget)
        self.label_A.setGeometry(QtCore.QRect(405, 59, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_A.setObjectName("label_A")
        self.label_A_s = QtWidgets.QLabel(self.widget)
        self.label_A_s.setGeometry(QtCore.QRect(415, 66, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_A_s.setFont(font)
        self.label_A_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_A_s.setObjectName("label_A_s")
        self.label_S = QtWidgets.QLabel(self.widget)
        self.label_S.setGeometry(QtCore.QRect(568, 59, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S.setFont(font)
        self.label_S.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_S.setObjectName("label_S")
        self.label_S_f = QtWidgets.QLabel(self.widget)
        self.label_S_f.setGeometry(QtCore.QRect(543, 46, 146, 192))
        self.label_S_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_S_f.setText("")
        self.label_S_f.setObjectName("label_S_f")
        self.label_S_b = QtWidgets.QLabel(self.widget)
        self.label_S_b.setGeometry(QtCore.QRect(540, 43, 152, 198))
        self.label_S_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(166, 166, 166);background-color: rgb(203, 175, 241);")
        self.label_S_b.setText("")
        self.label_S_b.setObjectName("label_S_b")
        self.label_S_s = QtWidgets.QLabel(self.widget)
        self.label_S_s.setGeometry(QtCore.QRect(578, 66, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S_s.setFont(font)
        self.label_S_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_S_s.setObjectName("label_S_s")
        self.label_H = QtWidgets.QLabel(self.widget)
        self.label_H.setGeometry(QtCore.QRect(728, 59, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_H.setFont(font)
        self.label_H.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_H.setObjectName("label_H")
        self.label_H_b = QtWidgets.QLabel(self.widget)
        self.label_H_b.setGeometry(QtCore.QRect(702, 43, 152, 198))
        self.label_H_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(92, 225, 230);background-color: rgb(77, 159, 232);")
        self.label_H_b.setText("")
        self.label_H_b.setObjectName("label_H_b")
        self.label_H_f = QtWidgets.QLabel(self.widget)
        self.label_H_f.setGeometry(QtCore.QRect(705, 46, 146, 192))
        self.label_H_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_H_f.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.label_H_f.setText("")
        self.label_H_f.setObjectName("label_H_f")
        self.label_H_s = QtWidgets.QLabel(self.widget)
        self.label_H_s.setGeometry(QtCore.QRect(738, 66, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_H_s.setFont(font)
        self.label_H_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_H_s.setObjectName("label_H_s")
        self.label_D_s = QtWidgets.QLabel(self.widget)
        self.label_D_s.setGeometry(QtCore.QRect(580, 381, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_D_s.setFont(font)
        self.label_D_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_D_s.setObjectName("label_D_s")
        self.label_D_f = QtWidgets.QLabel(self.widget)
        self.label_D_f.setGeometry(QtCore.QRect(543, 363, 146, 192))
        self.label_D_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_D_f.setText("")
        self.label_D_f.setObjectName("label_D_f")
        self.label_S2_s = QtWidgets.QLabel(self.widget)
        self.label_S2_s.setGeometry(QtCore.QRect(740, 381, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S2_s.setFont(font)
        self.label_S2_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                      "")
        self.label_S2_s.setObjectName("label_S2_s")
        self.label_2A_s = QtWidgets.QLabel(self.widget)
        self.label_2A_s.setGeometry(QtCore.QRect(255, 381, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_2A_s.setFont(font)
        self.label_2A_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                      "")
        self.label_2A_s.setObjectName("label_2A_s")
        self.label_C_b = QtWidgets.QLabel(self.widget)
        self.label_C_b.setGeometry(QtCore.QRect(51, 360, 152, 198))
        self.label_C_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 164, 164);background-color: rgb(199, 223, 100);")
        self.label_C_b.setText("")
        self.label_C_b.setObjectName("label_C_b")
        self.label_S2_f = QtWidgets.QLabel(self.widget)
        self.label_S2_f.setGeometry(QtCore.QRect(705, 363, 146, 192))
        self.label_S2_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;")
        self.label_S2_f.setText("")
        self.label_S2_f.setObjectName("label_S2_f")
        self.label_S2_b = QtWidgets.QLabel(self.widget)
        self.label_S2_b.setGeometry(QtCore.QRect(702, 360, 152, 198))
        self.label_S2_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;\n"
                                      "border-width: 5px;border-style: solid;border-color: rgb(201, 226, 101);background-color: rgb(255, 164, 164);")
        self.label_S2_b.setText("")
        self.label_S2_b.setObjectName("label_S2_b")
        self.label_2A_b = QtWidgets.QLabel(self.widget)
        self.label_2A_b.setGeometry(QtCore.QRect(215, 360, 152, 198))
        self.label_2A_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;\n"
                                      "border-width: 5px;border-style: solid;border-color: rgb(203, 175, 241);background-color: rgb(255, 189, 89);")
        self.label_2A_b.setText("")
        self.label_2A_b.setObjectName("label_2A_b")
        self.label_C_f = QtWidgets.QLabel(self.widget)
        self.label_C_f.setGeometry(QtCore.QRect(54, 363, 146, 192))
        self.label_C_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_C_f.setText("")
        self.label_C_f.setObjectName("label_C_f")
        self.label_2A_f = QtWidgets.QLabel(self.widget)
        self.label_2A_f.setGeometry(QtCore.QRect(218, 363, 146, 192))
        self.label_2A_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                      "border-bottom-right-radius: 10px;\n"
                                      "border-top-left-radius: 10px;\n"
                                      "border-bottom-left-radius: 10px;")
        self.label_2A_f.setText("")
        self.label_2A_f.setObjectName("label_2A_f")
        self.label_D = QtWidgets.QLabel(self.widget)
        self.label_D.setGeometry(QtCore.QRect(570, 374, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_D.setFont(font)
        self.label_D.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_D.setObjectName("label_D")
        self.label_D_b = QtWidgets.QLabel(self.widget)
        self.label_D_b.setGeometry(QtCore.QRect(540, 360, 152, 198))
        self.label_D_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "color: rgb(255, 85, 0);\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(255, 85, 0);background-color: rgb(231, 92, 178);")
        self.label_D_b.setText("")
        self.label_D_b.setObjectName("label_D_b")
        self.label_2A = QtWidgets.QLabel(self.widget)
        self.label_2A.setGeometry(QtCore.QRect(245, 374, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_2A.setFont(font)
        self.label_2A.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2A.setObjectName("label_2A")
        self.label_C = QtWidgets.QLabel(self.widget)
        self.label_C.setGeometry(QtCore.QRect(77, 374, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_C.setObjectName("label_C")
        self.label_C_s = QtWidgets.QLabel(self.widget)
        self.label_C_s.setGeometry(QtCore.QRect(87, 381, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_C_s.setFont(font)
        self.label_C_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_C_s.setObjectName("label_C_s")
        self.label_R_s = QtWidgets.QLabel(self.widget)
        self.label_R_s.setGeometry(QtCore.QRect(415, 381, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_R_s.setFont(font)
        self.label_R_s.setStyleSheet("color: rgb(32, 109, 180);\n"
                                     "")
        self.label_R_s.setObjectName("label_R_s")
        self.label_R_b = QtWidgets.QLabel(self.widget)
        self.label_R_b.setGeometry(QtCore.QRect(377, 360, 152, 198))
        self.label_R_b.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-width: 5px;border-style: solid;border-color: rgb(50, 179, 226);background-color: rgb(3, 151, 157);")
        self.label_R_b.setText("")
        self.label_R_b.setObjectName("label_R_b")
        self.label_R_f = QtWidgets.QLabel(self.widget)
        self.label_R_f.setGeometry(QtCore.QRect(381, 363, 146, 192))
        self.label_R_f.setStyleSheet("border-top-right-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-bottom-left-radius: 10px;")
        self.label_R_f.setText("")
        self.label_R_f.setObjectName("label_R_f")
        self.label_R = QtWidgets.QLabel(self.widget)
        self.label_R.setGeometry(QtCore.QRect(405, 374, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_R.setFont(font)
        self.label_R.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_R.setObjectName("label_R")
        self.label_S2 = QtWidgets.QLabel(self.widget)
        self.label_S2.setGeometry(QtCore.QRect(730, 374, 101, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(73)
        self.label_S2.setFont(font)
        self.label_S2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_S2.setObjectName("label_S2")
        self.label.raise_()
        self.label_F_b.raise_()
        self.label_login.raise_()
        self.lineEdit_username.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_L_b.raise_()
        self.label_L_s.raise_()
        self.label_L.raise_()
        self.label_F_s.raise_()
        self.label_F.raise_()
        self.label_L_f.raise_()
        self.label_F_f.raise_()
        self.label_A_b.raise_()
        self.label_A_s.raise_()
        self.label_A.raise_()
        self.label_S_b.raise_()
        self.label_S_s.raise_()
        self.label_S.raise_()
        self.label_H_b.raise_()
        self.label_H_s.raise_()
        self.label_H.raise_()
        self.label_C_b.raise_()
        self.label_S2_b.raise_()
        self.label_2A_b.raise_()
        self.label_D_b.raise_()
        self.label_C_s.raise_()
        self.label_R_b.raise_()
        self.label_2A_s.raise_()
        self.label_2A.raise_()
        self.label_R_s.raise_()
        self.label_R.raise_()
        self.label_D_s.raise_()
        self.label_D.raise_()
        self.label_S2_s.raise_()
        self.label_C.raise_()
        self.label_S2.raise_()
        self.label_2A_f.raise_()
        self.label_A_f.raise_()
        self.label_S_f.raise_()
        self.label_D_f.raise_()
        self.label_S2_f.raise_()
        self.label_H_f.raise_()
        self.label_C_f.raise_()
        self.label_R_f.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label_login.setText(_translate("Login", "Login & Sign Up"))
        self.pushButton.setText(_translate("Login", "Login"))
        self.pushButton_2.setText(_translate("Login", "Cancel"))
        self.label_L.setText(_translate("Login", "L"))
        self.label_L_s.setText(_translate("Login", "L"))
        self.label_F.setText(_translate("Login", "F"))
        self.label_F_s.setText(_translate("Login", "F"))
        self.label_A.setText(_translate("Login", "A"))
        self.label_A_s.setText(_translate("Login", "A"))
        self.label_S.setText(_translate("Login", "S"))
        self.label_S_s.setText(_translate("Login", "S"))
        self.label_H.setText(_translate("Login", "H"))
        self.label_H_s.setText(_translate("Login", "H"))
        self.label_D_s.setText(_translate("Login", "D"))
        self.label_S2_s.setText(_translate("Login", "S"))
        self.label_2A_s.setText(_translate("Login", "A"))
        self.label_D.setText(_translate("Login", "D"))
        self.label_2A.setText(_translate("Login", "A"))
        self.label_C.setText(_translate("Login", "C"))
        self.label_C_s.setText(_translate("Login", "C"))
        self.label_R_s.setText(_translate("Login", "R"))
        self.label_R.setText(_translate("Login", "R"))
        self.label_S2.setText(_translate("Login", "S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())

    
    

        
